version: 1.0.{build}
before_build:
- ps: nuget sources add -Name OneScriptAlpha -Source https://ci.appveyor.com/nuget/dmpas-onescript
- ps: nuget restore
init:
- ps: Set-WinSystemLocale ru-RU
- ps: Start-Sleep -s 5
- ps: Restart-Computer
build:
  verbosity: minimal
test_script:
- ps: nunit3-console --x86 NUnitTests\bin\Debug\NUnitTests.dll
